name: ci
on:
  workflow_dispatch:
    inputs:
      runjob:
        type: boolean
        required: true
        description: "skip or run job"
jobs:
  build:
    # runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runjob }}
    steps:
      - run: echo "run job 1"
  build2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.runjob == 'true' }}
    steps:
      - run: echo "run job 2"

    

